import type {
  FonctionGouvernance,
  HistoriqueStatut,
  Member,
  Participation,
  ProgressionParams,
  Role,
  ScreenKey,
  SessionReservee,
} from "./types";

const ALL: ScreenKey[] = [
  "accueil", "membres", "roles", "gouvernance", "participations",
  "sessions", "mon-espace", "parametres",
];

export const INITIAL_PARAMS: ProgressionParams = {
  participationsParNiveau: { 1: 2, 2: 4, 3: 6, 4: 8, 5: 10 },
  participationsPourConfirme: 6,
  absencesAvantRetrogradation: 2,
  presencesPourRecuperation: 2,
  seuilInvestisseurFcfa: 500_000,
  engagementMensuelConfirmeFcfa: 50_000,
  niveauMinGouvernance: 3,
};

export const INITIAL_ROLES: Role[] = [
  {
    id: "visiteur",
    label: "Invité / Visiteur",
    description: "Infos publiques, événements, demande d'adhésion.",
    tone: "muted",
    screens: ["accueil", "sessions", "mon-espace"],
    locked: true,
  },
  {
    id: "membre",
    label: "Membre",
    description: "Communauté, participations, espace personnel.",
    tone: "cyan",
    screens: ["accueil", "participations", "sessions", "mon-espace"],
    locked: true,
  },
  {
    id: "investisseur",
    label: "Membre Investisseur",
    description: "Sessions réservées + espace financier personnel.",
    tone: "premium",
    screens: ["accueil", "participations", "sessions", "mon-espace"],
    locked: true,
  },
  {
    id: "secretaire",
    label: "Secrétaire",
    description: "Gestion membres & participations (N3+).",
    tone: "navy",
    screens: ["accueil", "membres", "gouvernance", "participations", "sessions", "mon-espace"],
  },
  {
    id: "admin",
    label: "Administrateur",
    description: "Accès complet : rôles, paramètres, gouvernance.",
    tone: "danger",
    screens: ALL,
    locked: true,
  },
];

function fn(
  partial: Omit<FonctionGouvernance, "id" | "active"> & { id?: string; active?: boolean },
): FonctionGouvernance {
  return { id: partial.id ?? `fg-${Math.random().toString(36).slice(2, 8)}`, active: partial.active ?? true, ...partial };
}

export const INITIAL_MEMBERS: Member[] = [
  {
    id: "M-0001",
    nom: "Paul Stephy Arnaud",
    email: "ps.arnaud@finx.club",
    avatar: "PA",
    statut: "confirme",
    niveau: 5,
    badgeInvestisseur: true,
    roleId: "admin",
    fonctions: [],
    cotisation: "À jour",
    capitalInvesti: 2_500_000,
    adhesion: "01 Jan 2021",
    groupes: ["Direction"],
    nbPresences: 24,
    nbAbsences: 0,
    consecutives: 8,
    enRecuperation: false,
    grantScreens: [],
    denyScreens: [],
  },
  {
    id: "M-0284",
    nom: "Konan Kouassi Édouard",
    email: "kk.edouard@mail.com",
    avatar: "KK",
    statut: "actif",
    niveau: 3,
    badgeInvestisseur: true,
    roleId: "investisseur",
    fonctions: [
      fn({
        type: "president_groupe",
        groupeOuPole: "Groupe Étudiants",
        dateNomination: "15 Mar 2024",
        dureeMandat: "2 ans",
        responsabilites: "Animation du groupe étudiants, relais événements",
      }),
    ],
    cotisation: "À jour",
    capitalInvesti: 1_250_000,
    adhesion: "12 Jan 2022",
    groupes: ["Groupe Étudiants"],
    nbPresences: 7,
    nbAbsences: 1,
    consecutives: 2,
    enRecuperation: false,
    grantScreens: [],
    denyScreens: [],
  },
  {
    id: "M-0283",
    nom: "Ama Diallo Fanta",
    email: "ama.diallo@mail.com",
    avatar: "AD",
    statut: "confirme",
    niveau: 5,
    badgeInvestisseur: true,
    roleId: "investisseur",
    fonctions: [
      fn({
        type: "president_pole",
        groupeOuPole: "Pôle Investissement",
        dateNomination: "01 Juin 2023",
        dureeMandat: "3 ans",
        responsabilites: "Pilotage pôle investissement, reporting",
      }),
    ],
    cotisation: "À jour",
    capitalInvesti: 8_000_000,
    adhesion: "03 Mar 2021",
    groupes: ["Pôle Investissement"],
    nbPresences: 18,
    nbAbsences: 0,
    consecutives: 10,
    enRecuperation: false,
    grantScreens: ["membres"],
    denyScreens: [],
  },
  {
    id: "M-0282",
    nom: "Seydou Traoré",
    email: "seydou.t@mail.com",
    avatar: "ST",
    statut: "simple",
    niveau: 0,
    badgeInvestisseur: false,
    roleId: "membre",
    fonctions: [],
    cotisation: "En retard",
    capitalInvesti: 0,
    adhesion: "09 Juin 2023",
    groupes: [],
    nbPresences: 3,
    nbAbsences: 2,
    consecutives: 0,
    enRecuperation: true,
    grantScreens: [],
    denyScreens: [],
  },
  {
    id: "M-0281",
    nom: "Adjoua Marie-Claire",
    email: "adjoua.mc@mail.com",
    avatar: "AM",
    statut: "suspendu",
    niveau: 2,
    badgeInvestisseur: true,
    roleId: "investisseur",
    fonctions: [],
    cotisation: "Impayée",
    capitalInvesti: 920_000,
    adhesion: "22 Sep 2022",
    groupes: ["Groupe Cadres"],
    nbPresences: 5,
    nbAbsences: 3,
    consecutives: 0,
    enRecuperation: false,
    grantScreens: [],
    denyScreens: ["sessions"],
  },
  {
    id: "M-0280",
    nom: "Ibrahima Coulibaly",
    email: "ibrahima.c@mail.com",
    avatar: "IC",
    statut: "actif",
    niveau: 1,
    badgeInvestisseur: false,
    roleId: "membre",
    fonctions: [],
    cotisation: "À jour",
    capitalInvesti: 0,
    adhesion: "15 Nov 2023",
    groupes: ["Groupe Étudiants"],
    nbPresences: 2,
    nbAbsences: 0,
    consecutives: 2,
    enRecuperation: false,
    grantScreens: [],
    denyScreens: [],
  },
  {
    id: "M-0279",
    nom: "Nadia Bamba Koné",
    email: "nadia.bk@mail.com",
    avatar: "NK",
    statut: "actif",
    niveau: 4,
    badgeInvestisseur: false,
    roleId: "secretaire",
    fonctions: [
      fn({
        type: "secretaire",
        groupeOuPole: "Secrétariat général",
        dateNomination: "10 Jan 2024",
        dureeMandat: "2 ans",
        responsabilites: "Registre membres, PV, suivis de présence",
      }),
    ],
    cotisation: "À jour",
    capitalInvesti: 100_000,
    adhesion: "01 Fév 2023",
    groupes: ["Secrétariat"],
    nbPresences: 12,
    nbAbsences: 0,
    consecutives: 5,
    enRecuperation: false,
    grantScreens: [],
    denyScreens: [],
  },
  {
    id: "M-0275",
    nom: "Yannick Bah",
    email: "y.bah@mail.com",
    avatar: "YB",
    statut: "invite",
    niveau: 0,
    badgeInvestisseur: false,
    roleId: "visiteur",
    fonctions: [],
    cotisation: "—",
    capitalInvesti: 0,
    adhesion: "20 Jan 2025",
    groupes: [],
    nbPresences: 0,
    nbAbsences: 0,
    consecutives: 0,
    enRecuperation: false,
    grantScreens: [],
    denyScreens: [],
  },
];

export const INITIAL_PARTICIPATIONS: Participation[] = [
  { id: "P-001", memberId: "M-0284", date: "2025-01-10", type: "reunion", titre: "Réunion mensuelle Plateau", present: true },
  { id: "P-002", memberId: "M-0284", date: "2025-01-18", type: "evenement", titre: "Instant Invest — Marchés UEMOA", present: true },
  { id: "P-003", memberId: "M-0282", date: "2025-01-10", type: "reunion", titre: "Réunion mensuelle Plateau", present: false },
  { id: "P-004", memberId: "M-0282", date: "2025-01-18", type: "evenement", titre: "Instant Invest — Marchés UEMOA", present: false },
  { id: "P-005", memberId: "M-0280", date: "2025-01-10", type: "reunion", titre: "Réunion mensuelle Plateau", present: true },
  { id: "P-006", memberId: "M-0280", date: "2025-01-18", type: "evenement", titre: "Instant Invest — Marchés UEMOA", present: true },
  { id: "P-007", memberId: "M-0279", date: "2025-01-10", type: "reunion", titre: "Réunion mensuelle Plateau", present: true },
  { id: "P-008", memberId: "M-0283", date: "2025-01-22", type: "session_info", titre: "Session investisseurs Q1", present: true },
];

export const INITIAL_HISTORY: HistoriqueStatut[] = [
  {
    id: "H-001",
    memberId: "M-0282",
    date: "2025-01-18",
    ancienStatut: "actif",
    nouveauStatut: "simple",
    ancienNiveau: 1,
    nouveauNiveau: 0,
    motif: "2e absence — rétrogradation automatique",
    type: "retrogradation",
  },
  {
    id: "H-002",
    memberId: "M-0280",
    date: "2025-01-18",
    ancienStatut: "simple",
    nouveauStatut: "actif",
    ancienNiveau: 0,
    nouveauNiveau: 1,
    motif: "2 participations éligibles — passage N1",
    type: "montee_niveau",
  },
  {
    id: "H-003",
    memberId: "M-0284",
    date: "2024-11-02",
    ancienStatut: "actif",
    nouveauStatut: "actif",
    ancienNiveau: 2,
    nouveauNiveau: 3,
    motif: "6 participations — éligible gouvernance",
    type: "montee_niveau",
  },
];

export const INITIAL_SESSIONS: SessionReservee[] = [
  {
    id: "S-001",
    titre: "Perspectives de marché — Trimestre 1",
    date: "2025-02-20",
    heure: "18h00",
    lieu: "Visio + Plateau",
    lienVisio: "https://meet.finx.club/invest-q1",
    places: 40,
    inscrits: ["M-0001", "M-0284", "M-0283"],
    documents: ["Agenda Q1.pdf", "Note de conjoncture.pdf"],
  },
  {
    id: "S-002",
    titre: "Opportunités & projets de développement",
    date: "2025-05-15",
    heure: "17h30",
    lieu: "Siège FINX",
    lienVisio: "https://meet.finx.club/invest-q2",
    places: 35,
    inscrits: ["M-0001", "M-0283"],
    documents: [],
    replay: undefined,
  },
];
