import type { Member, Role, ScreenKey } from "./types";

const PUBLIC: ScreenKey[] = ["accueil", "programmes", "evenements", "partenaires", "documents", "mon-espace"];
const MEMBER: ScreenKey[] = [...PUBLIC, "souscription"];
const INVESTOR: ScreenKey[] = [...MEMBER, "investissements"];
const SECRETARY: ScreenKey[] = [...INVESTOR, "membres"];
const ADMIN: ScreenKey[] = [
  "accueil",
  "membres",
  "roles",
  "evenements",
  "programmes",
  "partenaires",
  "souscription",
  "investissements",
  "documents",
  "mon-espace",
  "backoffice",
];

export const INITIAL_ROLES: Role[] = [
  {
    id: "visiteur",
    label: "Invité / Visiteur",
    description: "Accès limité aux informations publiques et aux événements.",
    tone: "muted",
    screens: ["accueil", "programmes", "evenements", "partenaires", "mon-espace"],
    locked: true,
  },
  {
    id: "membre",
    label: "Membre",
    description: "Accès communauté, cotisations et souscriptions de base.",
    tone: "cyan",
    screens: MEMBER,
    locked: true,
  },
  {
    id: "investisseur",
    label: "Membre Investisseur",
    description: "Accès prioritaire aux dossiers, reportings et suivi capital.",
    tone: "premium",
    screens: INVESTOR,
    locked: true,
  },
  {
    id: "secretaire",
    label: "Secrétaire",
    description: "Gestion des membres et suivi administratif (niveau ≥ N3).",
    tone: "navy",
    screens: SECRETARY,
  },
  {
    id: "admin",
    label: "Administrateur",
    description: "Back-office complet : utilisateurs, rôles, droits d'accès.",
    tone: "danger",
    screens: ADMIN,
    locked: true,
  },
];

export const INITIAL_MEMBERS: Member[] = [
  {
    id: "M-0001",
    nom: "Paul Stephy Arnaud",
    email: "ps.arnaud@finx.club",
    avatar: "PA",
    statut: "confirme",
    niveau: 5,
    badgeInvestisseur: true,
    roleId: "admin",
    fonctions: ["Président Exécutif"],
    cotisation: "À jour",
    capital: "—",
    adhesion: "01 Jan 2021",
    grantScreens: [],
    denyScreens: [],
  },
  {
    id: "M-0284",
    nom: "Konan Kouassi Édouard",
    email: "kk.edouard@mail.com",
    avatar: "KK",
    statut: "actif",
    niveau: 3,
    badgeInvestisseur: true,
    roleId: "investisseur",
    fonctions: [],
    cotisation: "À jour",
    capital: "12 500 000 FCFA",
    adhesion: "12 Jan 2022",
    grantScreens: [],
    denyScreens: [],
  },
  {
    id: "M-0283",
    nom: "Ama Diallo Fanta",
    email: "ama.diallo@mail.com",
    avatar: "AD",
    statut: "confirme",
    niveau: 5,
    badgeInvestisseur: true,
    roleId: "investisseur",
    fonctions: ["Présidente de Pôle"],
    cotisation: "À jour",
    capital: "28 000 000 FCFA",
    adhesion: "03 Mar 2021",
    grantScreens: ["membres"],
    denyScreens: [],
  },
  {
    id: "M-0282",
    nom: "Seydou Traoré",
    email: "seydou.t@mail.com",
    avatar: "ST",
    statut: "simple",
    niveau: 0,
    badgeInvestisseur: false,
    roleId: "membre",
    fonctions: [],
    cotisation: "En retard",
    capital: "5 000 000 FCFA",
    adhesion: "09 Juin 2023",
    grantScreens: [],
    denyScreens: ["souscription"],
  },
  {
    id: "M-0281",
    nom: "Adjoua Marie-Claire",
    email: "adjoua.mc@mail.com",
    avatar: "AM",
    statut: "suspendu",
    niveau: 2,
    badgeInvestisseur: true,
    roleId: "investisseur",
    fonctions: [],
    cotisation: "Impayée",
    capital: "9 200 000 FCFA",
    adhesion: "22 Sep 2022",
    grantScreens: [],
    denyScreens: ["investissements", "souscription"],
  },
  {
    id: "M-0280",
    nom: "Ibrahima Coulibaly",
    email: "ibrahima.c@mail.com",
    avatar: "IC",
    statut: "actif",
    niveau: 1,
    badgeInvestisseur: false,
    roleId: "membre",
    fonctions: [],
    cotisation: "À jour",
    capital: "3 750 000 FCFA",
    adhesion: "15 Nov 2023",
    grantScreens: [],
    denyScreens: [],
  },
  {
    id: "M-0279",
    nom: "Nadia Bamba Koné",
    email: "nadia.bk@mail.com",
    avatar: "NK",
    statut: "actif",
    niveau: 4,
    badgeInvestisseur: false,
    roleId: "secretaire",
    fonctions: ["Secrétaire"],
    cotisation: "À jour",
    capital: "—",
    adhesion: "01 Fév 2023",
    grantScreens: [],
    denyScreens: [],
  },
  {
    id: "M-0275",
    nom: "Yannick Bah",
    email: "y.bah@mail.com",
    avatar: "YB",
    statut: "invite",
    niveau: 0,
    badgeInvestisseur: false,
    roleId: "visiteur",
    fonctions: [],
    cotisation: "—",
    capital: "—",
    adhesion: "20 Jan 2025",
    grantScreens: [],
    denyScreens: [],
  },
];
